"""
Django settings for visualflow project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from config.env_config import EnvConfig

# Fix Windows console encoding issues with Unicode/emoji characters
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.detach(), errors='replace')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.detach(), errors='replace')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Validate required environment variables on startup
try:
    EnvConfig.validate_required_env_vars()
except ValueError as e:
    print(f"Warning: {e}")
    print("Please check your .env file and ensure all required variables are set.")
except Exception as e:
    print(f"Warning: Could not validate environment variables: {e}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = EnvConfig.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = EnvConfig.DEBUG

BROWSER_RELOAD_ENABLED = DEBUG and EnvConfig.ENABLE_BROWSER_RELOAD

ALLOWED_HOSTS = EnvConfig.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'diagrams',  # Our main app
    *(['django_browser_reload'] if BROWSER_RELOAD_ENABLED else []),
]
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    *(['django_browser_reload.middleware.BrowserReloadMiddleware'] if BROWSER_RELOAD_ENABLED else []),
]

ROOT_URLCONF = 'visualflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'visualflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if EnvConfig.DB_TYPE == 'sqlite':
    # SQLite Configuration (default)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # PostgreSQL, MySQL, Oracle, or any other database
    _ca_cert_file = EnvConfig.get_ca_cert_file()
    DATABASES = {
        'default': {
            'ENGINE': f'django.db.backends.{EnvConfig.DB_TYPE}',
            'NAME': EnvConfig.DB_NAME,
            'USER': EnvConfig.DB_USER,
            'PASSWORD': EnvConfig.DB_PASSWORD,
            'HOST': EnvConfig.DB_HOST,
            'PORT': EnvConfig.DB_PORT,
            'OPTIONS': {
                'sslmode': EnvConfig.DB_SSL_MODE if EnvConfig.DB_SSL_REQUIRE else 'prefer',
                **({
                    'sslcert': EnvConfig.DB_SSL_CERT_PATH,
                    'sslkey': EnvConfig.DB_SSL_KEY_PATH,
                    'sslrootcert': _ca_cert_file,
                } if EnvConfig.DB_SSL_REQUIRE and any([
                    EnvConfig.DB_SSL_CERT_PATH, 
                    EnvConfig.DB_SSL_KEY_PATH, 
                    _ca_cert_file
                ]) else {})
            } if EnvConfig.DB_SSL_REQUIRE else {},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session configuration
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'diagrams': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

os.makedirs(BASE_DIR / 'logs', exist_ok=True)

from config.constants import AppConstants


GROQ_API_KEY = EnvConfig.GROQ_API_KEY
LANGCHAIN_API_KEY = EnvConfig.LANGCHAIN_API_KEY

APP_NAME = EnvConfig.APP_NAME
APP_VERSION = EnvConfig.APP_VERSION
