# Generated by Django 5.2.7 on 2025-10-09 18:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the template', max_length=100)),
                ('diagram_type', models.CharField(choices=[('uml', 'UML'), ('erd', 'ERD'), ('dfd', 'DFD'), ('flowchart', 'FLOWCHART'), ('system_design', 'SYSTEM_DESIGN'), ('custom', 'CUSTOM')], help_text='Type of diagram this template is for', max_length=20)),
                ('template_prompt', models.TextField(help_text='Template prompt with placeholders')),
                ('sample_uml', models.TextField(blank=True, help_text='Sample PlantUML code for this template', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this template generates', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Diagram Template',
                'verbose_name_plural': 'Diagram Templates',
                'ordering': ['diagram_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the session', primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text="User's textual prompt for diagram generation", max_length=2000)),
                ('diagram_type', models.CharField(choices=[('uml', 'UML'), ('erd', 'ERD'), ('dfd', 'DFD'), ('flowchart', 'FLOWCHART'), ('system_design', 'SYSTEM_DESIGN'), ('custom', 'CUSTOM')], help_text='Type of diagram to generate', max_length=20)),
                ('generated_uml', models.TextField(blank=True, help_text='Generated PlantUML code', null=True)),
                ('diagram_svg', models.TextField(blank=True, help_text='Generated SVG diagram content', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of diagram generation', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the session was last updated')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
            ],
            options={
                'verbose_name': 'Diagram Session',
                'verbose_name_plural': 'Diagram Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='diagrams_se_created_1cccf5_idx'), models.Index(fields=['diagram_type'], name='diagrams_se_diagram_13fd68_idx'), models.Index(fields=['status'], name='diagrams_se_status_f81635_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiagramFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1-5 stars')),
                ('feedback_text', models.TextField(blank=True, help_text="User's feedback text", null=True)),
                ('is_helpful', models.BooleanField(blank=True, help_text='Whether the user found the diagram helpful', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='diagrams.session')),
            ],
            options={
                'verbose_name': 'Diagram Feedback',
                'verbose_name_plural': 'Diagram Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
