# Generated by Django 5.2.7 on 2025-11-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagramfeedback',
            name='session',
        ),
        migrations.DeleteModel(
            name='DiagramTemplate',
        ),
        migrations.AlterField(
            model_name='session',
            name='generated_uml',
            field=models.TextField(blank=True, help_text='Generated Mermaid.js code', null=True),
        ),
        migrations.DeleteModel(
            name='DiagramFeedback',
        ),
    ]
