# Generated by Django 5.2.7 on 2026-02-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0002_contact_remove_diagramfeedback_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mermaid_debug_mode', models.BooleanField(default=False, help_text='Enable debug mode to show Mermaid code in diagram display')),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
