# Generated by Django 5.2.7 on 2026-04-18 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_appsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this diagram is visible to everyone'),
        ),
        migrations.AddField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this diagram session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagram_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['owner'], name='diagrams_se_owner_i_88da58_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_public'], name='diagrams_se_is_publ_ffee8c_idx'),
        ),
    ]
