name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 139.59.37.74
          username: root
          key: ${{ secrets.VISUALFLOW_DEPLOY_KEY }}
          timeout: 5m
          script: |
            set -e
            cd /root/app
            chmod +x deploy.sh
            ./deploy.sh
